# Generated by Django 3.2.9 on 2021-12-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
